#
# This workflow will run all the normal static tests (linting, unit, etc.), will
# make sure the build completes successfully, and will connect to a MongoDB Data API
# if merged to the main branch.
#

name: test

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
      env:
        MONGODB_API_URL: ${{secrets.MONGODB_API_URL}}
        MONGODB_API_KEY: ${{secrets.MONGODB_API_KEY}}
        MONGODB_DATABASE_NAME: ${{secrets.MONGODB_DATABASE_NAME}}
        MONGODB_CLUSTER_NAME: ${{secrets.MONGODB_CLUSTER_NAME}}
    - run: npm run build
